#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Alisu — DigitalOcean one-shot deployment script.
#
# Run THIS on the droplet (167.71.238.122) as root:
#
#   ssh root@167.71.238.122
#   curl -fsSL https://raw.githubusercontent.com/<your-handle>/alisu/main/scripts/deploy-do.sh -o deploy.sh
#   # — or paste this whole file —
#   chmod +x deploy.sh
#   SARVAM_API_KEY=sk_xxx REPO_URL=https://github.com/<you>/alisu.git ./deploy.sh
#
# It will:
#   1. install Node 20, git, nginx, certbot, build-essential
#   2. clone (or pull) the repo to /opt/alisu
#   3. install workspace deps and build the dashboard
#   4. write /opt/alisu/apps/server/.env with your Sarvam key
#   5. install pm2 and run the server as a managed process
#   6. configure nginx as a reverse proxy on port 80 (with WebSocket support)
#   7. (optional, if DOMAIN set) issue a Let's Encrypt cert and switch to HTTPS
#
# Re-running is safe: it pulls latest, rebuilds, and reloads pm2 + nginx.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Configurable env vars ───────────────────────────────────────────────────
SARVAM_API_KEY="${SARVAM_API_KEY:-}"            # required
REPO_URL="${REPO_URL:-https://github.com/your-handle/alisu.git}"
APP_DIR="${APP_DIR:-/opt/alisu}"
APP_USER="${APP_USER:-root}"                    # who pm2 runs as
DOMAIN="${DOMAIN:-}"                            # optional: e.g. alisu.example.com
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-}"      # required if DOMAIN set
PORT="${PORT:-3000}"                            # internal Fastify port

if [[ -z "$SARVAM_API_KEY" ]]; then
  echo "✗ SARVAM_API_KEY is required. Run: SARVAM_API_KEY=sk_xxx ./deploy.sh"
  exit 1
fi

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }

# ── 1. System packages ──────────────────────────────────────────────────────
log "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git nginx build-essential ca-certificates ufw

# Node 20 from NodeSource
if ! command -v node >/dev/null || [[ "$(node -v 2>/dev/null | cut -c2-3)" != "20" ]]; then
  log "Installing Node.js 20 LTS"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
node -v
npm -v

# pm2 (process manager — keeps the server alive across reboots)
if ! command -v pm2 >/dev/null; then
  log "Installing pm2"
  npm install -g pm2
fi

# ── 2. Code ─────────────────────────────────────────────────────────────────
if [[ ! -d "$APP_DIR/.git" ]]; then
  log "Cloning $REPO_URL into $APP_DIR"
  mkdir -p "$(dirname "$APP_DIR")"
  git clone "$REPO_URL" "$APP_DIR"
else
  log "Pulling latest in $APP_DIR"
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" reset --hard origin/main
fi

cd "$APP_DIR"

# ── 3. Install + build ──────────────────────────────────────────────────────
log "Installing npm dependencies"
npm install --no-audit --no-fund

log "Building dashboard"
( cd apps/dashboard && npm run build )

# ── 4. Server env ───────────────────────────────────────────────────────────
log "Writing apps/server/.env"
cat > "$APP_DIR/apps/server/.env" <<EOF
SARVAM_API_KEY=$SARVAM_API_KEY
PORT=$PORT
TELEPHONY_PROVIDER=local
RECORDING_DIR=/var/lib/alisu/recordings
EOF
mkdir -p /var/lib/alisu/recordings
chmod 750 "$APP_DIR/apps/server/.env"

# ── 5. pm2 process ──────────────────────────────────────────────────────────
log "Starting / reloading pm2 process 'alisu-server'"
cd "$APP_DIR/apps/server"
# Use ts-node directly so we don't need a separate compile step.
# Pass --update-env so pm2 picks up the new .env on every reload.
if pm2 describe alisu-server >/dev/null 2>&1; then
  pm2 reload alisu-server --update-env
else
  pm2 start --name alisu-server --interpreter node \
    "$APP_DIR/node_modules/.bin/ts-node" -- src/index.ts
  pm2 save
  pm2 startup systemd -u "$APP_USER" --hp "/$APP_USER" | tail -1 | bash || true
fi

# ── 6. Static dashboard via nginx ───────────────────────────────────────────
log "Configuring nginx"
NGINX_CONF=/etc/nginx/sites-available/alisu
SERVER_NAME="${DOMAIN:-_}"

cat > "$NGINX_CONF" <<NGINX
# Generated by deploy-do.sh — edits will be overwritten on next deploy.
upstream alisu_server { server 127.0.0.1:$PORT; }

server {
    listen 80;
    listen [::]:80;
    server_name $SERVER_NAME;

    # Larger client_max for any future audio uploads
    client_max_body_size 25m;

    # ── Static dashboard ─────────────────────────────────────────────────
    root $APP_DIR/apps/dashboard/dist;
    index index.html;

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # ── API + WebSocket → Fastify ────────────────────────────────────────
    location ~ ^/(api|dashboard-ws|media-stream|transcripts|complaints|calls|translate|incoming-call|handle-confirm|voice-token|transfer|audio|health|ws)(/|$) {
        proxy_pass         http://alisu_server;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade            \$http_upgrade;
        proxy_set_header   Connection         "upgrade";
        proxy_set_header   Host               \$host;
        proxy_set_header   X-Real-IP          \$remote_addr;
        proxy_set_header   X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  \$scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # Cache static assets aggressively (Vite produces hashed filenames)
    location ~* \.(?:css|js|woff2|svg|png|jpg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
NGINX

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/alisu
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl reload nginx
systemctl enable nginx

# ── 7. Firewall ─────────────────────────────────────────────────────────────
log "Configuring UFW firewall"
ufw allow OpenSSH || true
ufw allow 'Nginx Full' || true
yes | ufw enable || true

# ── 8. (Optional) HTTPS via Let's Encrypt ───────────────────────────────────
if [[ -n "$DOMAIN" && -n "$LETSENCRYPT_EMAIL" ]]; then
  log "Issuing Let's Encrypt certificate for $DOMAIN"
  apt-get install -y certbot python3-certbot-nginx
  certbot --nginx --non-interactive --agree-tos \
    -m "$LETSENCRYPT_EMAIL" -d "$DOMAIN" --redirect
elif [[ -n "$DOMAIN" ]]; then
  echo "ℹ Set LETSENCRYPT_EMAIL to enable HTTPS automatically."
fi

# ── Done ────────────────────────────────────────────────────────────────────
log "Done. Summary:"
echo "  • App dir       : $APP_DIR"
echo "  • Server (pm2)  : alisu-server on :$PORT"
echo "  • Dashboard     : served by nginx from $APP_DIR/apps/dashboard/dist"
echo "  • Recordings    : /var/lib/alisu/recordings"
echo "  • URL           : http${DOMAIN:+s}://${DOMAIN:-$(curl -s -4 ifconfig.me)}"
echo
echo "Useful commands:"
echo "  pm2 logs alisu-server     # tail server logs"
echo "  pm2 restart alisu-server  # bounce the process"
echo "  systemctl reload nginx    # reload reverse proxy"
echo "  cd $APP_DIR && git pull && ./scripts/deploy-do.sh   # redeploy"
